### ISSUE TITLE
Black and white tray icon not rendering correctly

### ISSUE THREAD

**Issue by wilfredom** [yakimka/CherryTomato#23] opened 2020-10-13 21:12 UTC
Title says it all:

![newicon](https://user-images.githubusercontent.com/15095683/95916815-16784600-0d5e-11eb-8df7-95328fd8567b.png)

The white box behind the tomato was not there before.

I'm on Manjaro Gnome (Mikah 20.1.1), fully updated, and running CherryTomato 1.0.0. I think this happened in the last update, though there was also a large Manjaro update, so, not sure what could have caused the change.

**Comment by yakimka** [comment] 2020-10-24 12:24
How did you enable black and white icon? I do not see that option in gnome shell

**Comment by wilfredom** [comment] 2020-10-29 02:23
Hey,

I use the Unite gnome extension, although the problem happens even without
the greyscale setting (see attached).

**Comment by wilfredom** [comment] 2020-10-30 19:51
Forgot to add: I'm on the latest version of Manjaro, using Gnome 3.36.6.

**Comment by yakimka** [comment] 2020-11-01 12:35
This extension does not work for me at all
![image](https://user-images.githubusercontent.com/28621349/97802891-3d37e700-1c4f-11eb-8783-347b846c9894.png)

**Comment by wilfredom** [comment] 2020-11-03 02:48
Weird. I also see that my previous screenshot didn't go through: even when I turn off the option, I still see the white square around the icon (which, as I understand correctly, is created by the Unite extension. When I disable the Unite extension, the cherry tomato icon goes to the dock).

![Screenshot from 2020-11-02 18-46-06](https://user-images.githubusercontent.com/15095683/97945267-de9c6700-1d3b-11eb-93a7-5a1fb2732408.png)
![Screenshot from 2020-11-02 18-47-00](https://user-images.githubusercontent.com/15095683/97945314-fffd5300-1d3b-11eb-8518-e9a8fb7d5fff.png)

**Comment by yakimka** [comment] 2021-02-27 20:26
Sorry, I can't reproduce this behavior. So I close this issue.

**Closed by yakimka** 2021-02-27 20:26 UTC
